### ISSUE TITLE
新規追加したファイルがgithubにpushできない。コミットまでは可能

### ISSUE THREAD

**Issue by iisora** [Yoshiyuki-Su/vue-study#13]
出力ログは以下の通りです

git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags origin refs/heads/master:refs/heads/master 
Pushing to https://github.com/Yoshiyuki-Su/vue-study.git
To https://github.com/Yoshiyuki-Su/vue-study.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Yoshiyuki-Su/vue-study.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Completed with errors, see above

**Comment by Yoshiyuki-Su** [comment]
上記って解決した？

**Comment by iisora** [comment]
一度ローカルリポジトリを削除してクローンし直したら治った！
masterにプルしたのはすまない。
